### ISSUE TITLE
Column width of the reports

### ISSUE THREAD

**Issue by itssanmitra** [tableau/tableau-viz-lwc-samples#8]
### Summary
The Tableau reports embedded in Salesforce flexi pages cannot be adjusted apart from the height. It would be good to provide scroll bars and also adjust the width of the column of Tableau reports within Salesforce.

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@itssanmitra Using the new Tableau View LWC, horizontal and vertical scrollbars should be available if the viz does not fit into the component's frame. Try enabling the Show Tabs or Show Toolbar checkboxes. If you run into issues using the new Tableau View LWC, please open a case through Salesforce.
